# DFRobot SEN0623 C1001 mmWave Human Detection Sensor
# https://wiki.dfrobot.com/SKU_SEN0623_C1001_mmWave_Human_Detection_Sensor

esphome:
  name: mmwave_sensor
  friendly_name: mmwave_sensor

esp32:
  board: esp32dev
  framework: 
    type: esp-idf

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret api

ota:
  platform: esphome
  password: !secret ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.84
    gateway: 192.168.1.1
    subnet: 255.255.255.0

web_server:
  port: 80

external_components:
  - source:
      type: git
      url: https://github.com/TroySK/esphome
      ref: component/dfrobot_sen0623
    components: [ dfrobot_sen0623 ]
    refresh: 1min

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200

dfrobot_sen0623:
  update_interval: 5s

# Core sensors
sensor:
  - platform: dfrobot_sen0623
    heart_rate:
      name: "Heart rate"
  - platform: dfrobot_sen0623
    breath_rate:
      name: "Breath rate"
  - platform: dfrobot_sen0623
    human_distance:
      name: "Human distance"
  - platform: dfrobot_sen0623
    human_move_range:
      name: "Human move range"

# Text sensors
text_sensor:
  - platform: dfrobot_sen0623
    status:
      name: "Operating mode"
  - platform: dfrobot_sen0623
    movement:
      name: "Movement type"

# Binary sensor
binary_sensor:
  - platform: dfrobot_sen0623
    presence:
      name: "Presence"

# Switches
switch:
  - platform: dfrobot_sen0623
    type: request_rate
    name: "Request rate"
  - platform: dfrobot_sen0623
    type: hp_led
    name: "HP Led Enabled"

# Buttons
button:
  - platform: dfrobot_sen0623
    type: reset
    name: "Reset"
  - platform: dfrobot_sen0623
    type: mode_fall
    name: "Fall mode"
  - platform: dfrobot_sen0623
    type: mode_sleep
    name: "Sleep mode"
  - platform: restart
    name: "Restart"