# DFRobot SEN0623 C1001 mmWave Human Detection Sensor

esphome:
  name: mmwave_sensor
  friendly_name: mmwave_sensor

esp32:
  board: esp32dev
  framework: 
    type: esp-idf

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret api

ota:
  platform: esphome
  password: !secret ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.84
    gateway: 192.168.1.1
    subnet: 255.255.255.0

web_server:
  port: 80

external_components:
  - source:
      type: git
      url: https://github.com/TroySK/esphome
      ref: component/dfrobot_sen0623
    components: [ dfrobot_sen0623 ]
    refresh: 1min

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200

dfrobot_sen0623:
  update_interval: 5s
  install_angle_x: 0
  install_angle_y: 0
  install_angle_z: 0
  install_height: 250

# Core sensors
sensor:
  - platform: dfrobot_sen0623
    heart_rate:
      name: "Heart rate"
  - platform: dfrobot_sen0623
    breath_rate:
      name: "Breath rate"
  - platform: dfrobot_sen0623
    human_distance:
      name: "Human distance"
  - platform: dfrobot_sen0623
    human_move_range:
      name: "Human move range"

  # Fall mode - installation
  - platform: dfrobot_sen0623
    install_angle_x:
      name: "Install Angle X"
  - platform: dfrobot_sen0623
    install_angle_y:
      name: "Install Angle Y"
  - platform: dfrobot_sen0623
    install_angle_z:
      name: "Install Angle Z"
  - platform: dfrobot_sen0623
    install_height:
      name: "Install Height"

  # Fall mode - data
  - platform: dfrobot_sen0623
    fall_state:
      name: "Fall State"
  - platform: dfrobot_sen0623
    static_residency:
      name: "Static Residency"
  - platform: dfrobot_sen0623
    static_residency_time:
      name: "Static Residency Time"
  - platform: dfrobot_sen0623
    fall_time:
      name: "Fall Time"
  - platform: dfrobot_sen0623
    fall_sensitivity:
      name: "Fall Sensitivity"
  - platform: dfrobot_sen0623
    fall_break_height:
      name: "Fall Break Height"
  - platform: dfrobot_sen0623
    track_x:
      name: "Track X"
  - platform: dfrobot_sen0623
    track_y:
      name: "Track Y"
  - platform: dfrobot_sen0623
    unmanned_time:
      name: "Unmanned Time"
  - platform: dfrobot_sen0623
    accumulated_height_duration:
      name: "Accumulated Height Duration"
  - platform: dfrobot_sen0623
    seated_distance:
      name: "Seated Distance"
  - platform: dfrobot_sen0623
    motion_distance:
      name: "Motion Distance"

  # Sleep mode - data
  - platform: dfrobot_sen0623
    in_bed:
      name: "In Bed"
  - platform: dfrobot_sen0623
    sleep_state:
      name: "Sleep State"
  - platform: dfrobot_sen0623
    wake_duration:
      name: "Wake Duration"
  - platform: dfrobot_sen0623
    light_sleep:
      name: "Light Sleep"
  - platform: dfrobot_sen0623
    deep_sleep:
      name: "Deep Sleep"
  - platform: dfrobot_sen0623
    sleep_quality:
      name: "Sleep Quality"
  - platform: dfrobot_sen0623
    sleep_disturbances:
      name: "Sleep Disturbances"
  - platform: dfrobot_sen0623
    sleep_quality_rating:
      name: "Sleep Quality Rating"
  - platform: dfrobot_sen0623
    unattended_time:
      name: "Unattended Time"
  - platform: dfrobot_sen0623
    sleep_deadline:
      name: "Sleep Deadline"
  - platform: dfrobot_sen0623
    breathe_state:
      name: "Breathe State"
  - platform: dfrobot_sen0623
    breathe_value:
      name: "Breathe Value"

text_sensor:
  - platform: dfrobot_sen0623
    status:
      name: "Operating mode"
  - platform: dfrobot_sen0623
    movement:
      name: "Movement type"
  - platform: dfrobot_sen0623
    fall_status:
      name: "Fall Status"
  - platform: dfrobot_sen0623
    sleep_status:
      name: "Sleep Status"
  - platform: dfrobot_sen0623
    static_residency:
      name: "Static Residency"

binary_sensor:
  - platform: dfrobot_sen0623
    presence:
      name: "Presence"

switch:
  - platform: dfrobot_sen0623
    type: request_rate
    name: "Request rate"
  - platform: dfrobot_sen0623
    type: hp_led
    name: "HP Led Enabled"
  - platform: dfrobot_sen0623
    type: auto_mode
    name: "Auto mode"

button:
  - platform: dfrobot_sen0623
    type: reset
    name: "Reset"
  - platform: dfrobot_sen0623
    type: mode_fall
    name: "Fall mode"
  - platform: dfrobot_sen0623
    type: mode_sleep
    name: "Sleep mode"
  - platform: restart
    name: "Restart"